version: '3.3'

services:
  app:
    build: .
    ports:
      - ''
    environment:
      POSTGRES_HOST: 
      POSTGRES_PORT: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
